name: mindverse
description: A spiritual and mystical mobile app with aura scanning, AI chat, horoscope, and meditation features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add custom fonts to your application, uncomment and configure:
  # fonts:
  #   - family: Arial
  #     fonts:
  #       - asset: assets/fonts/Arial.ttf
  #         weight: 400

